require_relative '../controllers/people_controller.rb'
require_relative '../views/people_view.rb'
require_relative '../models/person.rb'
require_relative '../models/address.rb'
require_relative '../models/phone.rb'
require 'pry'